### ISSUE TITLE
[Internal Error] Can't give them control

### ISSUE THREAD

**Issue by bakgom123** [codelive-project/thonny-codelive#12]
I invited my team members to my Thonny, but I can't give them control.
And this appears on their screens.
The host can't give the members control, and none of them can see my codes.
<img width="772" alt="KakaoTalk_Photo_2021-04-02-05-31-36" src="https://user-images.githubusercontent.com/81522323/113351330-ad20d980-9375-11eb-9846-f9077a5ff43d.png">

**Comment by bakgom123** [comment]
Traceback (most recent call last):
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/Users/abc/Library/Python/3.7/lib/python/site-packages/thonnycontrib/codelive/__init__.py", line 110, in join_session
    join_session_vanilla(top.data)
  File "/Users/abc/Library/Python/3.7/lib/python/site-packages/thonnycontrib/codelive/__init__.py", line 94, in join_session_vanilla
    name=data_sess["name"], topic=data_sess["topic"], broker=data_sess["broker"]
  File "/Users/abc/Library/Python/3.7/lib/python/site-packages/thonnycontrib/codelive/client.py", line 130, in join_session
    shared_editors=shared_editors,
  File "/Users/abc/Library/Python/3.7/lib/python/site-packages/thonnycontrib/codelive/client.py", line 101, in __init__
    self.enable_cursor_blink()
  File "/Users/abc/Library/Python/3.7/lib/python/site-packages/thonnycontrib/codelive/client.py", line 470, in enable_cursor_blink
    self._cursor_blink()
  File "/Users/abc/Library/Python/3.7/lib/python/site-packages/thonnycontrib/codelive/client.py", line 495, in _cursor_blink
    usrs = list(usrs)
TypeError: 'int' object is not iterable

**Comment by Samigirma1** [comment]
Thank you for finding the bug. It was from unintentionally added code for an unreleased feature.
